spring:
  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://3.235.51.93:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:

        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/products,/products/**,/admin/**

        - id: cart-service
          uri: http://cart-service:8083
          predicates:
            - Path=/cart,/cart/**

        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/orders,/orders/**

        - id: feedback-service
          uri: http://feedback-service:8085
          predicates:
            - Path=/feedback,/feedback/**